/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-highest": "#dae2fd",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-background": "#131b2e",
        "surface-container": "#eaedff",
        "on-primary-container": "#dad7ff",
        "secondary-fixed": "#e1e0ff",
        "on-primary": "#ffffff",
        "primary-fixed": "#e2dfff",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#c0c1ff",
        "on-secondary-fixed-variant": "#2f2ebe",
        "primary-container": "#4f46e5",
        "secondary": "#4648d4",
        "inverse-primary": "#c3c0ff",
        "tertiary-container": "#006e4b",
        "error": "#ba1a1a",
        "tertiary-fixed": "#6ffbbe",
        "surface-variant": "#dae2fd",
        "inverse-surface": "#283044",
        "surface-dim": "#d2d9f4",
        "outline": "#777587",
        "on-secondary-fixed": "#07006c",
        "tertiary-fixed-dim": "#4edea3",
        "on-surface-variant": "#464555",
        "on-tertiary-container": "#67f4b7",
        "surface-tint": "#4d44e3",
        "surface": "#faf8ff",
        "secondary-container": "#6063ee",
        "primary": "#3525cd",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#002113",
        "on-primary-fixed": "#0f0069",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#3323cc",
        "outline-variant": "#c7c4d8",
        "surface-container-low": "#f2f3ff",
        "tertiary": "#005338",
        "primary-fixed-dim": "#c3c0ff",
        "on-surface": "#131b2e",
        "on-secondary-container": "#fffbff",
        "inverse-on-surface": "#eef0ff",
        "surface-container-high": "#e2e7ff",
        "background": "#faf8ff",
        "surface-bright": "#faf8ff"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        gutter: "1.5rem",
        "gutter-mobile": "1rem",
        margin: "2rem",
        "space-sm": "0.5rem",
        "margin-mobile": "1rem"
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "headline-xl-mobile": ["Geist"],
        "code-sm": ["JetBrains Mono"],
        "headline-md": ["Geist"],
        "headline-sm": ["Geist"],
        "headline-xl": ["Geist"],
        "label-sm": ["Geist"],
        "headline-lg": ["Geist"],
        "body-lg": ["Inter"],
        "display-lg": ["Geist"],
        "display-lg-mobile": ["Geist"],
        "label-md": ["Geist"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "-0.003em", fontWeight: "400" }],
        "headline-xl-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "code-sm": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["15px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-xl": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-lg": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.011em", fontWeight: "400" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "display-lg-mobile": ["30px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "-0.006em", fontWeight: "400" }]
      }
    }
  }
};